export { default as ChatPage } from './chat/index'
export { default as UsersPage } from '../pages/users/index'
export { default as FriendsPage } from '../pages/friends/index'
export { default as SearchPage } from '../pages/search/index'
export { default as LoginPage } from '../pages/login/index'
